#define LWIP_HTTPD_CGI 1  // Enable CGI (Common Gateway Interface) support
#define LWIP_HTTPD_SSI 0
#define LWIP_HTTPD_SUPPORT_POST 0
#define LWIP_MDNS_RESPONDER 0
#define LWIP_HTTPD_SSI_MULTIPART 1

#define LWIP_HTTPD_SSI_INCLUDE_TAG 0

#define HTTPD_FSDATA_FILE "pico_fsdata.inc"
#define LWIP_HTTPD_DYNAMIC_FILE_READ  1
#define LWIP_HTTPD_DYNAMIC_HEADERS 1
#define LWIP_HTTPD_CUSTOM_FILES 1

#define JSON_BUFFER_SIZE 1024

//LWIP_DBG_OFF LWIP_DBG_OFF
#define LWIP_DEBUG LWIP_DBG_OFF
#define HTTPD_DEBUG LWIP_DBG_OFF
#define LWIP_DBG_MIN_LEVEL LWIP_DBG_LEVEL_SERIOUS
#define LWIP_DBG_TYPES_ON LWIP_DBG_ON

#define MOTOR_FRONT_RIGHT_GPIO 2
#define MOTOR_BACK_RIGHT_GPIO 4
#define MOTOR_FRONT_LEFT_GPIO 1
#define MOTOR_BACK_LEFT_GPIO 5